model_config:
  model: UNet1 #the directory to which the results are saved
  initial_filter_size: [64]
  kernel: [3]
  drop_out_rate: [0.2]
  input_size: [400, 400]    #[1536, 1536] #h, w 
  channel: 1
  num_class: 4
  model_type: 'TransUnet' #UNet, TransUnet
  dropout: False
  anydepth: False
train_config:
  loss: dice_bce_mc
  accuracy: dice_bce_mc
  optimizer: SGD #SGD
  lr_rate: [0.01]
  adaptive_lr: True
  weight_decay: [0.0001]
  batch_size: [2]
  epochs: 20
  early_stop: 25
  num_workers: 20
  seed:  [35, 42]
  use_cuda: True
dataset_config:
  train_path: ['/home/ocaki13/projects/ultrasound/processed_data/ultrasoundSegmentationDatasetv2_resized_won/fold1/train/']
  val_path: ['/home/ocaki13/projects/ultrasound/processed_data/ultrasoundSegmentationDatasetv2_resized_won/fold1/val/']
  test_path: ['/home/ocaki13/projects/ultrasound/processed_data/ultrasoundSegmentationDatasetv2_resized_won/fold1/test/']
  augmentation: True
  save_dir: usDeneme2
  class_names: ['background','Optic Nerve','Retina + Choroid','Sclera']
resume:
  flag: False
  path: hd_exp1_123_bs/models/last_epoch.pt
  epoch: 75

